In [3]:
x <- 1:100 
z <- x[x %% 3 != 0]
z
length(z)
y <- z[z %% 2 == 1]
y
length(y)

[1]   1   2   4   5   7   8  10  11  13  14  16  17  19  20  22  23  25  26  28
[20]  29  31  32  34  35  37  38  40  41  43  44  46  47  49  50  52  53  55  56
[39]  58  59  61  62  64  65  67  68  70  71  73  74  76  77  79  80  82  83  85
[58]  86  88  89  91  92  94  95  97  98 100

[1] 67

[1]  1  5  7 11 13 17 19 23 25 29 31 35 37 41 43 47 49 53 55 59 61 65 67 71 73
[26] 77 79 83 85 89 91 95 97

[1] 33

# Muestreos

## Reemplazos

In [9]:
library(gtools)

datos <- LETTERS

letras <- c(1,5,7,10)

urna <- datos[letras]

tam_muestra <- 4
tam_conjunto <- length(urna)

    
    # Orden y con remplazo
muestra_con_orden_con_reemplazo <- permutations(n = tam_conjunto, r=tam_muestra, v = urna, repeats.allowed = TRUE)

if (tam_muestra <= tam_conjunto){
    # Orden y sin remplazo    
muestra_con_orden_sin_reemplazo <- permutations(n = tam_conjunto, r=tam_muestra, v = urna, repeats.allowed = FALSE)

    # Sin orden y con remplazo    
muestra_sin_orden_con_reemplazo <- combinations(n = tam_conjunto, r=tam_muestra, v = urna, repeats.allowed = TRUE)

    # Sin orden y sin remplazo
muestra_sin_orden_sin_reemplazo <- combinations(n = tam_conjunto, r=tam_muestra, v = urna, repeats.allowed = FALSE)
}

# Orden y con remplazo

In [2]:
muestra_con_orden_con_reemplazo

[,1] [,2] [,3] [,4]
 [1,] 1    1     1    1  
 [2,] 1    1     1    5  
 [3,] 1    1     1    7  
 [4,] 1    1     1   10  
 [5,] 1    1     5    1  
 [6,] 1    1     5    5  
 [7,] 1    1     5    7  
 [8,] 1    1     5   10  
 [9,] 1    1     7    1  
[10,] 1    1     7    5  
[11,] 1    1     7    7  
[12,] 1    1     7   10  
[13,] 1    1    10    1  
[14,] 1    1    10    5  
[15,] 1    1    10    7  
[16,] 1    1    10   10  
[17,] 1    5     1    1  
[18,] 1    5     1    5  
[19,] 1    5     1    7  
[20,] 1    5     1   10  
[21,] 1    5     5    1  
[22,] 1    5     5    5  
[23,] 1    5     5    7  
[24,] 1    5     5   10  
[25,] 1    5     7    1  
[26,] 1    5     7    5  
[27,] 1    5     7    7  
[28,] 1    5     7   10  
[29,] 1    5    10    1  
[30,] 1    5    10    5  
[31,] ⋮    ⋮    ⋮    ⋮   
[32,] 10    7    1    7  
[33,] 10    7    1   10  
[34,] 10    7    5    1  
[35,] 10    7    5    5  
[36,] 10    7    5    7  
[37,] 10    7    5   10  
[38,] 10    7    7    1  
[39,] 10    7    7    5  
[40,] 10    7    7    7  
[41,] 10    7    7   10  
[42,] 10    7   10    1  
[43,] 10    7   10    5  
[44,] 10    7   10    7  
[45,] 10    7   10   10  
[46,] 10   10    1    1  
[47,] 10   10    1    5  
[48,] 10   10    1    7  
[49,] 10   10    1   10  
[50,] 10   10    5    1  
[51,] 10   10    5    5  
[52,] 10   10    5    7  
[53,] 10   10    5   10  
[54,] 10   10    7    1  
[55,] 10   10    7    5  
[56,] 10   10    7    7  
[57,] 10   10    7   10  
[58,] 10   10   10    1  
[59,] 10   10   10    5  
[60,] 10   10   10    7  
[61,] 10   10   10   10

# Orden y sin remplazo

In [3]:
muestra_con_orden_sin_reemplazo

[,1] [,2] [,3] [,4]
 [1,]  1    5    7   10  
 [2,]  1    5   10    7  
 [3,]  1    7    5   10  
 [4,]  1    7   10    5  
 [5,]  1   10    5    7  
 [6,]  1   10    7    5  
 [7,]  5    1    7   10  
 [8,]  5    1   10    7  
 [9,]  5    7    1   10  
[10,]  5    7   10    1  
[11,]  5   10    1    7  
[12,]  5   10    7    1  
[13,]  7    1    5   10  
[14,]  7    1   10    5  
[15,]  7    5    1   10  
[16,]  7    5   10    1  
[17,]  7   10    1    5  
[18,]  7   10    5    1  
[19,] 10    1    5    7  
[20,] 10    1    7    5  
[21,] 10    5    1    7  
[22,] 10    5    7    1  
[23,] 10    7    1    5  
[24,] 10    7    5    1

# Sin orden y con remplazo

In [4]:
muestra_sin_orden_con_reemplazo

[,1] [,2] [,3] [,4]
 [1,]  1    1    1    1  
 [2,]  1    1    1    5  
 [3,]  1    1    1    7  
 [4,]  1    1    1   10  
 [5,]  1    1    5    5  
 [6,]  1    1    5    7  
 [7,]  1    1    5   10  
 [8,]  1    1    7    7  
 [9,]  1    1    7   10  
[10,]  1    1   10   10  
[11,]  1    5    5    5  
[12,]  1    5    5    7  
[13,]  1    5    5   10  
[14,]  1    5    7    7  
[15,]  1    5    7   10  
[16,]  1    5   10   10  
[17,]  1    7    7    7  
[18,]  1    7    7   10  
[19,]  1    7   10   10  
[20,]  1   10   10   10  
[21,]  5    5    5    5  
[22,]  5    5    5    7  
[23,]  5    5    5   10  
[24,]  5    5    7    7  
[25,]  5    5    7   10  
[26,]  5    5   10   10  
[27,]  5    7    7    7  
[28,]  5    7    7   10  
[29,]  5    7   10   10  
[30,]  5   10   10   10  
[31,]  7    7    7    7  
[32,]  7    7    7   10  
[33,]  7    7   10   10  
[34,]  7   10   10   10  
[35,] 10   10   10   10

# Sin orden y sin remplazo

In [5]:
muestra_sin_orden_sin_reemplazo

[,1] [,2] [,3] [,4]
[1,] 1    5    7    10

# Conteos teóricos

In [6]:
tam_conjunto^tam_muestra

factorial(tam_conjunto)/factorial(tam_conjunto-tam_muestra)

factorial(tam_conjunto+tam_muestra-1)/(factorial(tam_muestra)*factorial((tam_conjunto+tam_muestra-1)-tam_muestra))

factorial(tam_conjunto)/(factorial(tam_muestra)*factorial(tam_conjunto-tam_muestra))

[1] 256

[1] 24

[1] 35

[1] 1

# Conteo por programa

In [7]:
dim(muestra_con_orden_con_reemplazo)[1]
dim(muestra_con_orden_sin_reemplazo)[1]
dim(muestra_sin_orden_con_reemplazo)[1]
dim(muestra_sin_orden_sin_reemplazo)[1]

[1] 256

[1] 24

[1] 35

[1] 1